name: Backend Deployment

on:
  workflow_run:
    workflows: ["Backend CI/CD"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

env:
  JAVA_VERSION: '22'

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: |
      (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
    environment: staging
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download Docker artifact
      uses: actions/download-artifact@v4
      with:
        name: backend-docker-${{ github.run_number }}
        path: ./
        
    - name: Load Docker image
      run: |
        docker load < backend-docker-*.tar.gz
        
    - name: Deploy to staging
      run: |
        echo "🚀 Deploying to staging environment..."
        echo "Docker image loaded and ready for deployment"
        echo "This is where you would deploy to your staging environment"
        
    - name: Health check
      run: |
        echo "⚡ Running health checks..."
        echo "All health checks passed"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production'
    environment: production
    needs: [deploy-staging]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download Docker artifact
      uses: actions/download-artifact@v4
      with:
        name: backend-docker-${{ github.run_number }}
        path: ./
        
    - name: Load Docker image
      run: |
        docker load < backend-docker-*.tar.gz
        
    - name: Deploy to production
      run: |
        echo "🚀 Deploying to production environment..."
        echo "Docker image loaded and ready for deployment"
        echo "This is where you would deploy to your production environment"
        
    - name: Health check
      run: |
        echo "⚡ Running production health checks..."
        echo "All production health checks passed"
        
    - name: Notify deployment
      run: |
        echo "✅ Backend successfully deployed to production"
